spring:
  application:
    name: License
  datasource:
    url: jdbc:mysql://localhost:3306/dbase
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true