spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/dbase
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

jwt:
  secret: DubovikovIgorVadimovichBKC220200
  expiration: 3600000